### ISSUE TITLE
CI: nightly NoInstall job is failing

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3758] opened 2021-07-13 16:02 UTC
**Bug description**:
The recently added nightly job for e2e tests using the NoInstall option is failing in the CI: https://github.com/openservicemesh/osm/actions/workflows/nightly-noinstall.yml

**Affected area (please mark with X where applicable)**:
- CI System                  [X]

**Expected behavior**:
The CI job should not fail.

**Comment by michelleN** [comment] 2021-09-15 20:43
Why is the nightly job failing? I see it is still failing intermittently.

**Comment by michelleN** [comment] 2021-09-15 20:44
Is the root cause of this issue https://github.com/openservicemesh/osm/issues/3755?

**Comment by nshankar13** [comment] 2021-09-15 22:45
@michelleN That issue with the port exclusion test was not an intermittent failure - that was a persistent failure that was only resolved when we changed the namespace names between the pod level and global tests.

The intermittent failures we are seeing now in the NoInstall Nightly Job could be related to what was causing that previous error but I'm not 100 percent sure.

**Comment by shashankram** [comment] 2021-09-22 18:12
@nshankar13 If this is not an issue anymore, please close this. If this is still an issue, could you share an update on the failure?

**Comment by michelleN** [comment] 2021-09-28 16:55
@shalier - are you still investigating this?

**Comment by nshankar13** [comment] 2021-09-28 17:50
@shashankram @michelleN I will close this issue and open a separate one for intermittent failures (unrelated to this original issue).

**Closed** 2021-09-28 17:50 UTC
Labels: bug, area/CI, area/tests
