### ISSUE TITLE
Enforce single mesh via Helm

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#4193] opened 2021-09-29 23:46 UTC
**Please describe the Improvement and/or Feature Request**
As of today, single mesh can be enforced only via the CLI, we should improve this and ensure that the enforce single mesh logic is moved to helm so that users have the same experience.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment] 2022-01-25 22:55
Duplicate of https://github.com/openservicemesh/osm/issues/2147

**Closed by shashankram** 2022-01-25 22:55 UTC
