### ISSUE TITLE
Add SMI Traffic Split (v1alpha4) support in the routes v2 feature 

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2368] opened 2021-01-25 20:56 UTC
The routes v2 feature is an experimental feature which changes the way we program routes via RDS on the envoy sidecar proxies running next to each application Pod [link to proposal coming]. It currently supports SMI Traffic Access policies. If you enable the feature via the ROUTES_V2 env variable and run this demo, you'll see the once SMI policies are enabled, a source Pod that has been enabled via an SMI Traffic Target object will be able to talk to the destination specified in the policy and a destination will be able to accept requests at certain route configuration (path, method, headers, etc. specified in the SMI TrafficTarget)

This issue is to track the work to support SMI Traffic Split v1alpha4. If an SMI Traffic Split policy is applied, the outbound routes of all relevant client Pod proxies should be updated with the routing configuration specified in the SMI Traffic Split resource.

**Comment by snehachhabria** [comment] 2021-02-10 01:41
Based on offline discussion this will not be implemented as a part of routesv2 refactor and is an enhancement that will come later. Removing routesv2 label and milestone 0.8

**Comment by addozhang** [comment] 2021-02-22 03:03
@snehachhabria does this mean that the split upgreade (to v1alpha3 or v1alpha4) won't be include in milestone 0.8?

**Comment by snehachhabria** [comment] 2021-03-03 00:12
@addozhang yes that's right, we will most probably work on this in milestone 0.9

**Comment by shashankram** [comment] 2022-07-08 16:28
Duplicate of https://github.com/openservicemesh/osm/issues/4880

**Closed by shashankram** 2022-07-08 16:28 UTC
Labels: size/L, area/SMI, priority/P2
