### ISSUE TITLE
Namespace in termination state indefinitely

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#1879] opened 2020-10-21 01:55 UTC
**Bug description**:

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment] 2020-10-21 16:15
@eduser25 this bug doesn't seem to have any description. Kindly fill in the issue template.

**Comment by shashankram** [comment] 2020-10-21 17:13
Duplicate of #1880

**Closed by shashankram** 2020-10-21 17:13 UTC
Labels: bug
