### ISSUE TITLE
port-forward script failed for bookbuyer

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2840] opened 2021-03-12 22:17 UTC
**Bug description**:
Following https://github.com/openservicemesh/osm/blob/release-v0.8/docs/content/docs/install/manual_demo/_index.md, after deploying the app yamls, running`./scripts/port-forward-all.sh` failed for bookbuyer:

```console
kubectl port-forward -n bookbuyer bookbuyer-79bbd489d8-j52jr 8080:14001 
Forwarding from 127.0.0.1:8080 -> 14001
Forwarding from [::1]:8080 -> 14001
Handling connection for 8080
Handling connection for 8080
E0312 13:20:14.085451   61171 portforward.go:400] an error occurred forwarding 8080 -> 14001: error forwarding port 14001 to pod c52b91ecb68a1a33500d3f097c4f22298521abc05d4d048de2d4e33b2728bb92, uid : exit status 1: 2021/03/12 21:20:14 socat[8027] E connect(5, AF=2 127.0.0.1:14001, 16): Connection refused
```
Seems the reason for this failure is that as of commit 65f4f8545daf the readme is pointing to the yamls in main and main does not have the new image tags that carry the port change for bookbuyer.
 
**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by allenlsy** [comment] 2021-05-24 23:55
Looks like this bug is fixed. Tested with OSM v0.8.2 following the reproduce description above. After running `port-forward-all.sh`, the error message `portforward.go:400] an error occurred forwarding 8080 -> 14001:` didn't show up.

**Comment by shashankram** [comment] 2021-05-25 00:02
> Looks like this bug is fixed. Tested with OSM v0.8.2 following the reproduce description above. After running `port-forward-all.sh`, the error message `portforward.go:400] an error occurred forwarding 8080 -> 14001:` didn't show up.

Thanks @allenlsy for verifying. Closing this issue as "not reproducible".

**Closed by shashankram** 2021-05-25 00:02 UTC
Labels: bug
