### ISSUE TITLE
TrafficSplit service should removed from weighted cluster in route configuration

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2091] opened 2020-11-19 07:23 UTC
**Bug description**:

Split config:

![image](https://user-images.githubusercontent.com/2224492/99634038-d30aa900-2a7a-11eb-8da8-2f12a3219acc.png)

Section of route config dump

![image](https://user-images.githubusercontent.com/2224492/99634135-f170a480-2a7a-11eb-9537-6487abedfbec.png)

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:

There should be only split backed service existing in routing weighted cluster.

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): build from master
- Kubernetes version (use `kubectl version`): 1.17
- Size of cluster (number of worker nodes in the cluster): 4
- Others:

**Comment by snehachhabria** [comment] 2020-11-19 08:17
Duplicate of issue : #1979

**Comment by addozhang** [comment] 2020-11-19 08:26
@snehachhabria  oh, let me check.

**Comment by addozhang** [comment] 2020-11-19 08:31
@snehachhabria It is not resolved yet? can be reproduced with master version.

**Comment by snehachhabria** [comment] 2020-11-19 08:51
@addozhang yes its not yet resolved, we have a PR : https://github.com/openservicemesh/osm/pull/2035 that's in progress and will fix it in a cleaner manner

**Comment by shashankram** [comment] 2020-11-19 17:27
> Duplicate of issue : #1979

Closing this is as a duplicate.

**Closed by shashankram** 2020-11-19 17:27 UTC
Labels: bug
