### ISSUE TITLE
No warning if incorrect yaml is applied for Traffic Split 

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3615] opened 2021-06-17 09:11 UTC
**Bug description**:
For traffic split if weights are distributed in improper way like all weights don`t sum up to 100 or all weight`s sum > 100. We dont get a error message that yaml is incorrect.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [X ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:
apply the yaml with irregular weights like 1000, -200 etc. the yaml will be applied successfully without error. 
**How was OSM installed?**:
- minikube for k8s cluster
- then followed https://release-v0-8.docs.openservicemesh.io/docs/install/manual_demo/
**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): Version: v0.8.4
- Kubernetes version (use `kubectl version`): v1.15
- Size of cluster (number of worker nodes in the cluster):1
- Others:

**Comment by shashankram** [comment] 2021-06-17 15:56
Hey @mudit-01, as it stands, SMI traffic split does not require the total weight distributed across backends to be <=100. You could set up a split such that the weight exceeds 100, and traffic distribution to a backend will be computed as `<backend-weight>/<total-weight>`.

This concern should be raised with the SMI community at https://github.com/servicemeshinterface/smi-spec.

The SMI  traffic split CRD does not enforce positive integers for the weight in their CRD definition, which is the cause of this problem:
https://github.com/servicemeshinterface/smi-sdk-go/blob/a143f8bc96eccdf5fc8a66d0c1622591104c77e0/crds/split.yaml#L63-L65

**Comment by michelleN** [comment] 2021-09-21 16:59
Closing this issue out for now with @shashankram's explanation. @mudit-01 - feel free to re-open if it doesn't make sense or if you're seeing a specific issue/error. Thank you

**Closed by michelleN** 2021-09-21 16:59 UTC
Labels: bug, area/SMI
