### ISSUE TITLE
Integrate OSM and OSM Health

### ISSUE THREAD

**Issue by jaellio** [openservicemesh/osm#4101] opened 2021-09-13 17:54 UTC
**Please describe the Improvement and/or Feature Request**

Integrate osm-health into the OSM cli as an `osm health` subcommand.

A single tool for everything OSM-related will simplify the customer's experience.

Suggestions/Requirements:
- Speed up CI by only running jobs relevant to osm-health
- Increase code coverage

**Scope (please mark with X where applicable)**
- CLI Tool                   [ x ]
- Debugging                  [ x ]

**Possible use cases**

**Comment by allenlsy** [comment] 2022-02-10 18:56
I think we have two approaches here: 

1. Move code from osm-health to osm. 
2. Keep osm-health repo and import it in osm

Option 2 has some benefits. By doing so, two code base are separated. Their development process can be more independent. But osm-health is already importing osm repo, thus this approach may have circular dependency.

**Comment by shashankram** [comment] 2022-04-21 18:10
Closing this as it is a duplicate of https://github.com/openservicemesh/osm/issues/4634 which is already in-progress.

**Closed by shashankram** 2022-04-21 18:10 UTC
Labels: size/M
