### ISSUE TITLE
Create Flagger demo for OSM

### ISSUE THREAD

**Issue by asridharan** [openservicemesh/osm#315] opened 2020-03-17 06:54 UTC
[Flagger ](https://www.weave.works/oss/flagger/) is a Kubernetes operator that enables canary deployments on various service mesh. It already supports SMI and works with LinkerD. Given its popularity and our support for SMI we should look at supporting flagger and make sure our traffic split implementation satisfies Flagger's requirements. This would be a good correctness check for OSM.

**Comment by snehachhabria** [comment] 2021-05-21 21:05
closing this issue as its a duplicate of #1700

**Closed by snehachhabria** 2021-05-21 21:05 UTC
Labels: kind/needs-upstream-coordination, size/L
