### ISSUE TITLE
Envoy deprecated option 'envoy.type.matcher.v3.RegexMatcher.GoogleRE2.max_program_size'

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1847] opened 2020-10-14 23:39 UTC
The Envoy logs contain a deprecation warning, which should be addressed:

```
[2020-10-14 23:34:27.798][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.type.matcher.v3.RegexMatcher.GoogleRE2 Using deprecated option 'envoy.type.matcher.v3.RegexMatcher.GoogleRE2.max_program_size' from file regex.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
```

This is visible when the demo us running and Bookstore (for instance) logs are observed with: `./demo/tail-bookstore-envoy.sh bookstore-v1`

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by shashankram** [comment] 2020-10-14 23:55
This is strange because it should have been fixed by 29be79c6df41c7e457c04edded231af392bf6c90.

@draychev could you check if this is a false alarm?

**Comment by snehachhabria** [comment] 2020-10-15 23:01
I am not able to reproduce the error locally and do not see any warnings on the envoy. @draychev  please could you double check if you are still seeing the issue ?

**Comment by snehachhabria** [comment] 2020-10-19 22:10
I re-ran the demo a couple of times and was unbale to reproduce the error. I checked the logs on the envoy of bookbuyer, bookstore-v1 and bookstore-v2 and did not find the related warning. 

Closing the issue for now and we can re-open it if the problems comes up again

**Closed by snehachhabria** 2020-10-19 22:10 UTC
Labels: P2, control plane, improvement / feature request
