### ISSUE TITLE
Integrate OSM with SMI Conformance tool

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3194] opened 2021-04-19 16:51 UTC
**Please describe the Improvement and/or Feature Request**
Integrate OSM with SMI Conformance tool. This is something we'll need to run ourselves and push results. 

**Scope (please mark with X where applicable)**
- New Functionality          [ X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X ]
- CI System                  [X ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Indicates to community OSM's SMI compliance and what features they support.

https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit#

**Comment by shashankram** [comment] 2022-01-25 22:44
Duplicate of https://github.com/openservicemesh/osm/issues/3948

**Closed by shashankram** 2022-01-25 22:44 UTC
