### ISSUE TITLE
IngressBackend for a grpc service running in OSM mesh is not accepting the connection.

### ISSUE THREAD

**Issue by rcpandula** [openservicemesh/osm#5265] opened 2022-12-09 12:48 UTC
**Bug description**:
Hi,  In my application, I am exposing an ingress endpoint for a grpc service running in a OSM mesh. For some reasons I am not able to communicate with the service using the ingress end point.

The below files are uploaded as part of the attachment 
Deployment/Service/Ingress/Ingressbackend/osm-mesh-config/Error log from the envoy sidecar proxy running in the target pod and ingress log. 

[OSMIssue.zip](https://github.com/openservicemesh/osm/files/10194834/OSMIssue.zip)

**Affected area (please 
mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ x]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by rcpandula** [comment] 2022-12-09 12:53
I have been trying to fix or find the root cause for this issue, but could not find any breakthrough. I am really need a help...

First thing, does OSM supports a ingress backend for grpc service...? When I looked at the template of the ingressbackend, it has only two types of ports http or https....
kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: periodicscript-v10
  namespace: uop
spec:
  backends:
  - name: periodicscript-v10
    port:
      number: 8080
      protocol: https # or http. No GRPC support... does it required or not...?
    tls: 
      skipClientCertValidation: false
  sources:
  - kind: Service
    namespace: ingress-nginx
    name: ingress-nginx-controller
  - kind: AuthenticatedPrincipal
    name: ingress-nginx.ingress-nginx.cluster.local

I am getting the below errors from the envoy proxy: 
[2022-12-09 12:44:56.519][18][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:88] tls inspector: new connection accepted
[2022-12-09 12:44:56.519][18][trace][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:175] tls inspector: recv: 746
[2022-12-09 12:44:56.519][18][debug][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:20] original_dst: new connection accepted
[2022-12-09 12:44:56.519][18][trace][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:66] original_dst: set destination to 10.1.7.126:8080
[2022-12-09 12:44:56.519][18][debug][conn_handler] [source/server/active_stream_listener_base.cc:34] closing connection from 10.1.7.145:57660: no matching filter chain found

FYI... the normal https services are working fine without any issue... it is problem with only GRPC services.... 

Please let me know if I am missing anything or does OSM supports it or not.... this has impact on our next release of our product.

**Comment by shashankram** [comment] 2022-12-10 01:12
Duplicate of https://github.com/openservicemesh/osm/issues/5247

**Closed by shashankram** 2022-12-10 01:12 UTC
