### ISSUE TITLE
A destination should validate that the request is coming from a client/Pod that is allowed by validating a service account referenced in the certificate presented by the client.

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1891] opened 2020-10-22 15:06 UTC
We are currently associating a service account with a single service and thus baking in the service information in certificate. During the mTLS handshake, some SAN matching happens and the server determines if the service listed in the certificate from the client is allowed to talk to it.

This presents issues when
1. there are multiple Pods with different Service Accounts that are mapped to a single Service
2. there is a Pod with not Service attached to it trying to make requests to a destination service

These scenarios don't really work today. This issue is to add ServiceAccount to a service's certificate and remove the Kubernetes service information.

**Comment by shashankram** [comment] 2020-12-22 18:31
> We are currently associating a service account with a single service and thus baking in the service information in certificate. During the mTLS handshake, some SAN matching happens and the server determines if the service listed in the certificate from the client is allowed to talk to it.
> 

This is no longer true, resolved by https://github.com/openservicemesh/osm/issues/1965.

> These scenarios don't really work today. This issue is to add ServiceAccount to a service's certificate and remove the Kubernetes service information.

Duplicate of #1965 , which has already been addressed in v0.6.0.

**Closed by shashankram** 2020-12-22 18:31 UTC
Labels: size/L
