### ISSUE TITLE
cli: Create CLI tool to run troubleshooting tooling

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#2879] opened 2021-03-15 22:03 UTC
This GitHub Issue is for the design and implementation of a new OSM CLI tool (for instance: `osm trouble`), which runs a certain set of functions and inspects the Kubernetes cluster, SMI CRDs, Ingress, Services, Endpoints, Envoys (and other sidecars), Envoy configs and points to potential issues, even offers potential fixes.

  - [ ] Design a high level framework
    - [ ] `osm trouble --?` - what options could be provided to this?
    - [ ] The tool should ask the operator to provide as much context around the issue they are troubleshooting as possible (optional CLI arguments or interactive questions)
      - [ ] provide source pod
      - [ ] provide destination pod
      - [ ] provide namespace where the issue is
      - [ ] is there a specific SMI policy that we are having issues with?
      - [ ] is there certain Service Account or Service which is relevant   

The tool would run various functions for scenarios we have added to `pkg/troubleshooter`
  - `hasAccess(sourcePod, destinationPod)`
  - or `hasAccess(sourceServiceAccount, destServiceAccount)`
  - or `envoyHasInboundPolicy(service)`

(ideas) Questions the tool could/should answer:
  - `osm trouble --namespace=irc`  - provide everything we know about the namespace `irc` from the perspective of OSM:
    - is OSM enabled on that namespace
    - is it enabled for Envoy injection
    - is it annotated for metrics collection 
    - is this namespace port of a mesh? which mesh
    - list services and service accounts
    - show matrix of pods that have access to each other

  - `osm trouble --pod=xyz`  - gives all the context of a pod
    - are metrics enabled,
    - is it injected,
    - what services does it host,
    - what service cacount,
    - what does it have access to etc.
    - Is it affected by Ingress.
    - Is egress alowed.

  - other troubleshooter ideas
    - is a mesh installed at all
    - what namespaces are annotated for injection
    - what namespaces are annotated for metrics
  - are there other OSMs installed on the cluster
  - are there any other Service Meshes (not OSM) that are installed
  - are there other sidecars (pods with more than 1 container)

**Comment by shashankram** [comment] 2021-09-15 21:12
Duplicate of osm-health, and we have https://github.com/openservicemesh/osm/issues/4101 to track osm-health integration into osm cli.

**Closed by shashankram** 2021-09-15 21:12 UTC
Labels: size/M, area/debugging, priority/P2
