### ISSUE TITLE
outboundIPRangeExclusionList for internal IP ranges for AKS cluster does not work

### ISSUE THREAD

**Issue by SoujanyaMangipudi** [openservicemesh/osm#4375] opened 2021-11-24 00:37 UTC
On OSM v 0.11 with AKS cluster we are trying to use outboundIPRangeExclusionList to enable egress passthrough on sidecar for internal IP ranges for AKS. Following are the configurations added to mesh config. Post updating mesh config we did a rollout restart of our service pods. However, pod start up continues to fail when connecting to Azure Key Vault libraries. When we set enableEgress to true pod startup works fine. This issue looks related to egress on side car. We had istio service mesh deployed on the same cluster and the same IP range exclusions worked fine with istio side car configurations. Please assist in debugging this issue

![image](https://user-images.githubusercontent.com/19557867/143150075-a30a96d1-eacc-4baf-bab0-d2034b436894.png)

Pod describe osm-init container
![image](https://user-images.githubusercontent.com/19557867/143150206-64192ed4-ff92-458a-afd1-cedd52ab31cf.png)

**Comment by shashankram** [comment] 2021-11-24 16:43
@SoujanyaMangipudi it seems like when you disable egress, some IP addresses that are not in the exclusion list are being used as the destination for the requests. Based on our conversation offline, it seemed to indicate HTTP requests are being made with the host header `ip:port`, e.g. `10.240.10.30:15901`. OSM currently does not support making HTTP requests to services/apps with host headers not matching the service FQDN. See https://github.com/openservicemesh/osm/issues/2097 for more details.

Could you confirm this is the issue you see from the envoy logs for requests that are failing?

**Comment by SoujanyaMangipudi** [comment] 2021-11-29 20:30
As discussed, logs related to access using ip:port are unrelated to the egress issue. Enabling full egress on cluster resolves the startup errors that we are seeing. Exclusion of same set of IP ranges worked with istio service mesh but does not seem to work with OSM.

**Comment by shashankram** [comment] 2021-11-30 06:01
> As discussed, logs related to access using ip:port are unrelated to the egress issue. Enabling full egress on cluster resolves the startup errors that we are seeing. Exclusion of same set of IP ranges worked with istio service mesh but does not seem to work with OSM.

@SoujanyaMangipudi Please share the exact envoy logs for the requests that are failing. Without this, this issue cannot be root caused.

**Comment by shashankram** [comment] 2021-12-07 17:53
This seems to be due to a misconfiguration as noted in https://github.com/openservicemesh/osm/issues/4378#issuecomment-988145430. Closing this.

**Closed by shashankram** 2021-12-07 17:53 UTC
Labels: bug
