### ISSUE TITLE
(refactor): Centralize informer handling

### ISSUE THREAD

**Issue by keithmattix** [openservicemesh/osm#4793] opened 2022-06-07 16:09 UTC
**Please describe the Improvement and/or Feature Request**

We currently tightly couple our informers to specific objects (e.g. [k8s controller](https://github.com/openservicemesh/osm/blob/main/pkg/k8s/client.go#L48), [configurator](https://github.com/openservicemesh/osm/blob/main/pkg/configurator/client.go#L35), [smi](https://github.com/openservicemesh/osm/blob/main/pkg/smi/client.go#L71), and [policy](https://github.com/openservicemesh/osm/blob/main/pkg/policy/client.go#L32)). The drawback to this approach is that no other component of the code can access these informer caches, respond to events, or otherwise interact with k8s objects except by:

1. depending on one of the aforementioned objects (creating coupling where it may not need to be)
2. creating new informers and duplicating the event handling/caching (opening the door for inconsistencies between the two caches)

I'm proposing that we centralize our informer handling in one object whose pointer can be passed around to any other object that may need to access an informer. This prevents engineers from having to create new, expensive informers, and it allows us to have opinionated patterns for informer use.

**Scope (please mark with X where applicable)**
- Envoy Control Plane        [X]

**Possible use cases**

**Comment by shashankram** [comment] 2022-06-07 17:55
@keithmattix I believe this is a duplicate of https://github.com/openservicemesh/osm/issues/4551.  Do you agree?

**Comment by keithmattix** [comment] 2022-06-07 18:05
Oh I completely forgot that issue existed. Yeah this is the same thing; feel free to close

**Closed** 2022-06-07 18:10 UTC
Labels: kind/refactor
