### ISSUE TITLE
init container always running as root even when sidecar enablePrivilegedInitContainer flag not set

### ISSUE THREAD

**Issue by Shrizo** [openservicemesh/osm#4388] opened 2021-12-05 09:03 UTC
**Bug description**: Even when the meshconfig has enablePrivilegedInitContainer set to false, the injected sidecar image tries to run as root user, which causes the sidecar container to fail with the following:

Error: container has runAsNonRoot and image will run as root (pod: "<pod name>", container: osm-init)

This results in the pod not coming up with Init:CreateContainerConfigError

I have verified via 'kubectl get pod -o yaml <pod name>' that the init container has the following under the security context:
securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: false

Init container image: mcr.microsoft.com/oss/openservicemesh/init:v0.11.1

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: Sidecar init container doesn't run as root user and the pod comes up.

**Steps to reproduce the bug (as precisely as possible)**: 
1. Onboard the namespace to osm with 'osm namespace add <namespace>'
2. Restart all pods in namespace with 'kubectl delete pods --all -n  <namespace>'
3. Wait for pods to come up but they fail to

**How was OSM installed?**: osm installed via azure using 
az aks enable-addons --resource-group $RG --name $CLUSTER_NAME --addons open-service-mesh
All default values used during installation.

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): v0.11.1
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"b55a30656180655e4773309bc68268b87394142f", GitTreeState:"clean", BuildDate:"2021-11-01T16:42:19Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Size of cluster (number of worker nodes in the cluster): 5
- Others:

**Comment by allenlsy** [comment] 2022-01-07 21:53
I cannot reproduce this issue. Can you try again?

I used:

* Azure AKS with OSM addon.
* OSM version is 0.11.1
* `enablePrivilegedInitContainer` is confirmed set to false.

When I checked the osm-init container definition, I neither found `securityContext` section.

![image](https://user-images.githubusercontent.com/872876/148612270-25ce6ab6-8391-4077-8050-650015a4335c.png)

**Comment by Shrizo** [comment] 2022-01-24 06:25
I tried again, and once again the osm-init container is failling to come up.  

 Warning  Failed                  5s (x6 over 66s)  kubelet                  Error: container has runAsNonRoot and image will run as root (pod: "<podname>_dev(5f1e8a6e-5536-4c7c-815d-90151ac98cdc)", container: osm-init)

Likewise, my osm-init container has a security context section when I run 'k get pod <podname> -o yaml'

![image](https://user-images.githubusercontent.com/11233757/150732504-2c239fa0-e01d-4252-a8fd-95059a86e901.png)

**Comment by SanyaKochhar** [comment] 2022-01-24 21:40
@Shrizo could you provide the security contexts of the pod and the container (not the init container)? I am going to try and repro with all the same security context conditions

**Comment by SanyaKochhar** [comment] 2022-01-24 21:40
> Even when the meshconfig has enablePrivilegedInitContainer set to false, the injected sidecar image tries to run as root user, which causes the sidecar container to fail

Note that privileged init container is disabled because "privileged" grants more permissions than  root -- this elevated permission is not required except in very specific conditions (ex: on certain k8s distros). The init container is independently set to run as root (user 0) because it requires root permissions to finish scheduling. I suspect this error is caused by some other security context conflicts at pod vs container level

**Comment by Shrizo** [comment] 2022-01-26 20:08
Thanks for explaining the difference between privileged and root - I didn't realize there was one at first.

The security context on the envoy container:
```
securityContext:
      runAsUser: 1500
```

The security context on my container:
```
securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
```

The security context on the pod:
```
  securityContext:
    fsGroup: 1001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
```

I see there is a mismatch as you stated between the pod and container security contexts.  If this is set and required for the pod for security reasons, how will setting the uid of the init container user to 0 (root) help?

**Comment by SanyaKochhar** [comment] 2022-01-27 13:47
@Shrizo I was able to repro this with your security contexts. I believe the cause is that containers default to user ID 0 when `runAsUser` is not set, so when you set `runAsNonRoot: true` at the pod level but do not explicitly set the UID of the containers, pod tries to validate non-root while container tries to run as root and you get an error. The original `CreateContainerConfigError` error from osm-init will get resolved by the change in our next release that sets the osm-init to root. Based on my repro using the upcoming release, you will then get the same error on your app container. You should be able resolve this by setting a `runAsUser` value explicitly in either the pod or container security context. Could you try this out once v1.0.0 is out on the AKS add-on and let me know if you run into any errors?

> If this is set and required for the pod for security reasons, how will setting the uid of the init container user to 0 (root) help?

osm-init does have to run as root to finish scheduling, but you may apply the security contexts you require for security reasons to the pod which will apply it to any containers that do not have a user ID set in their security contexts.

**Comment by shashankram** [comment] 2022-02-02 21:07
> @Shrizo I was able to repro this with your security contexts. I believe the cause is that containers default to user ID 0 when `runAsUser` is not set, so when you set `runAsNonRoot: true` at the pod level but do not explicitly set the UID of the containers, pod tries to validate non-root while container tries to run as root and you get an error. The original `CreateContainerConfigError` error from osm-init will get resolved by the change in our next release that sets the osm-init to root. Based on my repro using the upcoming release, you will then get the same error on your app container. You should be able resolve this by setting a `runAsUser` value explicitly in either the pod or container security context. Could you try this out once v1.0.0 is out on the AKS add-on and let me know if you run into any errors?
> 
> > If this is set and required for the pod for security reasons, how will setting the uid of the init container user to 0 (root) help?
> 
> osm-init does have to run as root to finish scheduling, but you may apply the security contexts you require for security reasons to the pod which will apply it to any containers that do not have a user ID set in their security contexts.

@SanyaKochhar can we document the app requirements around SecurityContext at https://main--osm-docs.netlify.app/docs/guides/app_onboarding/prereqs/

**Closed** 2022-02-09 00:04 UTC
Labels: bug
