### ISSUE TITLE
Owner reference on application services fails to get applied when replica count of osm-controller is increased to 2

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#4182] opened 2021-09-28 18:23 UTC
**Bug description**: We the osm-controller replica count is increased to two, the owner reference for the application secrets fails to get applied and the following errors are observed : 

`{"level":"error","component":"kube-controller","error":"Operation cannot be fulfilled on secrets \"envoy-bootstrap-config-0c5bcd72-54ea-4fe3-8515-e2371177344e\": the object has been modified; please apply your changes to the latest version and try again","time":"2021-09-28T18:17:17Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookwarehouse/envoy-bootstrap-config-0c5bcd72-54ea-4fe3-8515-e2371177344e to reference Pod bookwarehouse/bookwarehouse-6556558d8b-tb4w2"}
{"level":"error","component":"kube-controller","error":"Operation cannot be fulfilled on secrets \"envoy-bootstrap-config-39f14641-2d3d-44c4-b74e-7e6530755e73\": the object has been modified; please apply your changes to the latest version and try again","time":"2021-09-28T18:17:20Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookwarehouse/envoy-bootstrap-config-39f14641-2d3d-44c4-b74e-7e6530755e73 to reference Pod bookwarehouse/mysql-0"}
{"level":"error","component":"kube-controller","error":"Operation cannot be fulfilled on secrets \"envoy-bootstrap-config-bd47f985-6aea-4bd3-8873-4409a2684756\": the object has been modified; please apply your changes to the latest version and try again","time":"2021-09-28T18:17:24Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookstore/envoy-bootstrap-config-bd47f985-6aea-4bd3-8873-4409a2684756 to reference Pod bookstore/bookstore-v1-6d9b685f7c-pf58f"}
{"level":"error","component":"kube-controller","error":"Operation cannot be fulfilled on secrets \"envoy-bootstrap-config-8b349088-5a89-4ac7-b31e-0f71fd43037f\": the object has been modified; please apply your changes to the latest version and try again","time":"2021-09-28T18:17:29Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookstore/envoy-bootstrap-config-8b349088-5a89-4ac7-b31e-0f71fd43037f to reference Pod bookstore/bookstore-v2-bd794f689-fgfn7"}
{"level":"error","component":"kube-controller","error":"Operation cannot be fulfilled on secrets \"envoy-bootstrap-config-fd95dd88-5f79-4b68-93cf-4449740c82ab\": the object has been modified; please apply your changes to the latest version and try again","time":"2021-09-28T18:17:33Z","file":"announcement_handlers.go:61","message":"Failed to update OwnerReference for Secret bookbuyer/envoy-bootstrap-config-fd95dd88-5f79-4b68-93cf-4449740c82ab to reference Pod bookbuyer/bookbuyer-59f7b7cf59-p2kg4"}`

This behavior isn't desired and osm should be able to handle updates with multiple control planes

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**: the above error message should not appear on the controller pod

**Steps to reproduce the bug (as precisely as possible)**: Run the osm demo off the main branch by increasing the replica count of osm controller to 2 

**How was OSM installed?**: 

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment] 2021-09-28 18:32
Duplicate of https://github.com/openservicemesh/osm/issues/3776.

**Closed by shashankram** 2021-09-28 18:32 UTC
Labels: bug
