### ISSUE TITLE
Support different liveness/readiness probes on more than one container in a pod

### ISSUE THREAD

**Issue by dantdj** [openservicemesh/osm#4948] opened 2022-07-28 13:18 UTC
**Please describe the Improvement and/or Feature Request**

Currently the automatic health probe forwarding (described here: https://release-v1-2.docs.openservicemesh.io/docs/guides/health_checks/health_probes/) only handles automatically generating forwarding rules in the injected Envoy container for one container's configured probe within a pod. This should instead be able to handle generating configuration for forwarding liveness/readiness probes for multiple containers within a pod.

**Further Info**
Apologies in advance if I've just missed something, but it seems to be the case that - as the liveness/readiness probe URLs in container config are replaced with just `/osm-liveness-probe` and `/osm-readiness-probe` respectively, and the rewriting within the injected OSM Envoy sidecar only affects those URLs  - it's impossible to have multiple containers with different probes within a pod, as only one URL per probe is available. 

As the current handling of probes will replace every container's liveness/readiness probe URLs in their configuration, this can cause unforeseen problems where probes start talking to entirely different URLs than they're meant to when adopting OSM. I haven't validated but I think the injected OSM Envoy pod just gets configured to forward through the last container's set of probes.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [X]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

This would allow multiple containers within a pod to have separate liveness/readiness checks while still going through OSM.

**Comment by lorenzo-biava** [comment] 2022-09-09 09:31
@dantdj Exactly. And there is no indication (in the doc, or validation during the mutation of the pod) that the config is invalid. So you get persistent failures on the other sets of probes, as Envoy listeners might not even be configured (say your last container has a TCP probe, ports 15901/2 won't have any listener at all).

A use case of ours is to add tracing sidecars in a Pod, and we would like to check that they are indeed alive and ready, to avoid losing traces. Other similar use cases based on sidecar containers would apply.

At the very least, this limitation should be added to the [doc](https://release-v1-2.docs.openservicemesh.io/docs/guides/health_checks/health_probes/#troubleshooting) explicitly.
And then the Pod should not get created, the mutatingwebhook should fail and reject it.

Looks like a duplicate of https://github.com/openservicemesh/osm/issues/3773 anyways.
@jaellio any thoughts?

**Comment by keithmattix** [comment] 2022-09-09 23:14
Thanks for bringing this to our attention. #3773 was closed due to inactivity, and the underlying issue still persists. I took a stab at a fix in #5106; I believe this should fix your issue!

**Comment by dantdj** [comment] 2022-09-10 16:01
Hey Keith - thanks for looking at this! I'll keep an eye on that PR :)

**Closed** 2022-09-21 20:22 UTC

**Comment by keithmattix** [comment] 2022-09-21 20:24
This fix should be released with OSM v1.3
