### ISSUE TITLE
Osm-controller restarts due to "concurrent map writes"

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2552] opened 2021-02-18 20:22 UTC
**Bug description**:
```
{"level":"info","component":"osm-controller/main","time":"2021-02-18T20:09:20Z","file":"osm-controller.go:112","message":"Starting osm-controller dev; dc255fb167894d70ab0d0c3302d53f2aae5d3e2a; 2021-02-18-12:08"}
{"level":"info","component":"osm-controller/main","time":"2021-02-18T20:09:20Z","file":"osm-controller.go:124","message":"Feature flags: {\"Backpressure\":false,\"RoutesV2\":false,\"WASMStats\":false}"}
W0218 20:09:20.665596       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"info","component":"osm-controller/main","time":"2021-02-18T20:09:20Z","file":"osm-controller.go:166","message":"Initial ConfigMap osm-config: {\n    \"PermissiveTrafficPolicyMode\": false,\n    \"Egress\": true,\n    \"EnableDebugServer\": true,\n    \"PrometheusScraping\": true,\n    \"UseHTTPSIngress\": false,\n    \"TracingEnable\": false,\n    \"TracingAddress\": \"\",\n    \"TracingPort\": 0,\n    \"TracingEndpoint\": \"\",\n    \"EnvoyLogLevel\": \"debug\",\n    \"ServiceCertValidityDuration\": \"24h\",\n    \"OutboundIPRangeExclusionList\": \"\",\n    \"EnablePrivilegedInitContainer\": true\n}"}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:126","message":"Namespace controller client started"}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:141","message":"Waiting informer for Namespaces cache sync..."}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:141","message":"Waiting informer for Services cache sync..."}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:141","message":"Waiting informer for ServiceAccounts cache sync..."}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:141","message":"Waiting informer for Pods cache sync..."}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:141","message":"Waiting informer for Endpoints cache sync..."}
{"level":"info","component":"kube-controller","time":"2021-02-18T20:09:20Z","file":"client.go:151","message":"Caches for [Namespaces Services ServiceAccounts Pods Endpoints] synced successfully"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:60","message":"SMI Client started"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:85","message":"Starting informer: TrafficSplit"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:85","message":"Starting informer: HTTPRouteGroup"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:85","message":"Starting informer: TCPRoute"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:85","message":"Starting informer: TrafficTarget"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:20Z","file":"client.go:90","message":"[SMI Client] Waiting for informers' cache to sync: TrafficSplit, HTTPRouteGroup, TCPRoute, TrafficTarget"}
{"level":"info","component":"mesh-spec","time":"2021-02-18T20:09:21Z","file":"client.go:98","message":"[SMI Client] Cache sync finished for [TrafficSplit HTTPRouteGroup TCPRoute TrafficTarget]"}
{"level":"info","component":"osm-controller/main","time":"2021-02-18T20:09:21Z","file":"osm-controller.go:311","message":"Created CA bundle Kubernetes secret osm-ca-bundle in namespace osm-system"}
{"level":"info","component":"kube-ingress","time":"2021-02-18T20:09:21Z","file":"client.go:51","message":"Ingress client started"}
{"level":"info","component":"kube-ingress","time":"2021-02-18T20:09:21Z","file":"client.go:58","message":"Waiting for Ingress informer cache sync"}
{"level":"info","component":"kube-ingress","time":"2021-02-18T20:09:21Z","file":"client.go:66","message":"Cache sync finished for Ingress informer"}
{"level":"info","component":"mesh-catalog","time":"2021-02-18T20:09:21Z","file":"catalog.go:16","message":"Create a new Service MeshCatalog."}
{"level":"info","component":"configurator","time":"2021-02-18T20:09:21Z","file":"validating_webhook.go:127","message":"Starting configmap webhook server on port: 9093"}
{"level":"info","component":"configurator","time":"2021-02-18T20:09:21Z","file":"validating_webhook.go:368","message":"Finished updating CA Bundle for ValidatingWebhookConfiguration osm-webhook-osm"}
{"level":"info","component":"utilities","time":"2021-02-18T20:09:21Z","file":"grpc.go:20","message":"Setting up ADS gRPC server..."}
{"level":"info","component":"http-server","time":"2021-02-18T20:09:21Z","file":"httpserver.go:67","message":"Starting API Server on :9092"}
{"level":"info","component":"http-server","time":"2021-02-18T20:09:21Z","file":"httpserver.go:67","message":"Starting API Server on :9091"}
{"level":"info","component":"utilities","time":"2021-02-18T20:09:21Z","file":"grpc.go:58","message":"[grpc][ADS] Started server on: [::]:15128"}
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 257 [running]:
runtime.throw(0x1d1120f, 0x15)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72 fp=0xc0015f53a0 sp=0xc0015f5370 pc=0x434682
runtime.mapassign_faststr(0x19fc860, 0xc0007dcc90, 0xc000bfb680, 0x4, 0xc001408c60)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:291 +0x3de fp=0xc0015f5408 sp=0xc0015f53a0 pc=0x4133fe
github.com/openservicemesh/osm/pkg/envoy/rds.aggregateRoutesByHost(0xc0006e47e0, 0x1cf8898, 0x2, 0xc001408c60, 0x1, 0x1, 0xc0007dcc90, 0xc000150100, 0x1b, 0x64, ...)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/rds/response.go:135 +0x3ae fp=0xc0015f5638 sp=0xc0015f5408 pc=0x1800c4e
github.com/openservicemesh/osm/pkg/envoy/rds.NewResponse(0x204ab60, 0xc00004da40, 0xc0015b6a80, 0xc000952400, 0x2042ec0, 0xc0001817c0, 0x2032e80, 0xc00008aa80, 0xc0015f5f00, 0x4d3838, ...)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/rds/response.go:84 +0x115a fp=0xc0015f5e88 sp=0xc0015f5638 pc=0x17fffda
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).newAggregatedDiscoveryResponse(0xc000c6f740, 0xc0015b6a80, 0xc000952400, 0x2042ec0, 0xc0001817c0, 0x3, 0xc000a7d3e0, 0xc003d04360ff87f4)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/ads/response.go:145 +0x24d fp=0xc0015f6058 sp=0xc0015f5e88 pc=0x1806f6d
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).sendTypeResponse(0xc000c6f740, 0x1d5d23b, 0x3c, 0xc0015b6a80, 0xc00090b330, 0xc000952400, 0x2042ec0, 0xc0001817c0, 0x0, 0x0)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/ads/response.go:30 +0x402 fp=0xc0015f6540 sp=0xc0015f6058 pc=0x1805492
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).sendAllResponses(0xc000c6f740, 0xc0015b6a80, 0xc00090b330, 0x2042ec0, 0xc0001817c0)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/ads/response.go:67 +0x3e4 fp=0xc0015f6888 sp=0xc0015f6540 pc=0x1805f14
github.com/openservicemesh/osm/pkg/envoy/ads.(*Server).StreamAggregatedResources(0xc000c6f740, 0x20349e0, 0xc00090b320, 0x0, 0x0)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/envoy/ads/stream.go:164 +0x9c5 fp=0xc0015f7c18 sp=0xc0015f6888 pc=0x1808255
github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3._AggregatedDiscoveryService_StreamAggregatedResources_Handler(0x1bdfc80, 0xc000c6f740, 0x202d180, 0xc0010f6840, 0x302cbd0, 0xc000c9fb00)
	/Users/kalya/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.8/envoy/service/discovery/v3/ads.pb.go:298 +0xad fp=0xc0015f7c60 sp=0xc0015f7c18 pc=0x14de20d
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000907080, 0x20395a0, 0xc0009caa80, 0xc000c9fb00, 0xc000c15e30, 0x2fe23c0, 0x0, 0x0, 0x0)
	/Users/kalya/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1237 +0xcd1 fp=0xc0015f7e38 sp=0xc0015f7c60 pc=0x1462101
google.golang.org/grpc.(*Server).handleStream(0xc000907080, 0x20395a0, 0xc0009caa80, 0xc000c9fb00, 0x0)
	/Users/kalya/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:1317 +0xcd6 fp=0xc0015f7f68 sp=0xc0015f7e38 pc=0x1463936
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000bfa2a0, 0xc000907080, 0x20395a0, 0xc0009caa80, 0xc000c9fb00)
	/Users/kalya/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:722 +0xa1 fp=0xc0015f7fb8 sp=0xc0015f7f68 pc=0x14705d1
runtime.goexit()
	/usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0015f7fc0 sp=0xc0015f7fb8 pc=0x466f61
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/kalya/go/pkg/mod/google.golang.org/grpc@v1.27.0/server.go:720 +0xa1

goroutine 1 [chan receive]:
main.main()
	/Users/kalya/go/src/github.com/ksubrmnn/osm/cmd/osm-controller/osm-controller.go:253 +0x1465

goroutine 18 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x3001180)
	/Users/kalya/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:1010 +0x8b
created by k8s.io/klog.init.0
	/Users/kalya/go/pkg/mod/k8s.io/klog@v1.0.0/klog.go:411 +0xd6

goroutine 19 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x3001260)
	/Users/kalya/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
	/Users/kalya/go/pkg/mod/k8s.io/klog/v2@v2.0.0/klog.go:416 +0xd6

goroutine 37 [chan receive]:
github.com/openservicemesh/osm/pkg/signals.RegisterExitHandlers.func1(0xc00095c840, 0xc00064afe8)
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/signals/signals.go:20 +0x34
created by github.com/openservicemesh/osm/pkg/signals.RegisterExitHandlers
	/Users/kalya/go/src/github.com/ksubrmnn/osm/pkg/signals/signals.go:17 +0xed
```
**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]

**Expected behavior**:
OSM controller should not crash and restart

**Steps to reproduce the bug (as precisely as possible)**:
Cannot repro, seems to be a timing issue

**How was OSM installed?**:
run-osm-demo.sh on OpenShift

Built off of a branch with latest commit: 1bec41f73b1bf43497fdcfe8a47281d1dc6f76b3

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): Testing from main with changes slated for 0.8.0
- Kubernetes version (use `kubectl version`): v1.18.3+f561b20
- Size of cluster (number of worker nodes in the cluster): 3 workers, 3 control plane nodes
- Others:

**Comment by phillipgibson** [comment] 2021-02-25 14:59
@ksubrmnn what priority level should this be?

**Comment by michelleN** [comment] 2021-03-02 00:30
Closing as this part of the codebase has been refactored and deleted. Was not able to reproduce.

**Closed by michelleN** 2021-03-02 00:30 UTC
Labels: bug
